<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useCartStore } from '@/stores/cart'
import { getVisitorId } from '@/services/eventViewService'
import { clearCheckoutAttempt, getOrCreateCheckoutToken, rememberOrderToken } from '@/utils/checkoutStorage'
import { getCheckoutOrder, initializeCheckout, quoteCheckout, verifyCheckoutPayment } from '@/services/checkoutService'
import { loadPaystack } from '@/utils/paystack'

const POLL_INTERVAL_MS = 2500
const MAX_POLL_MS = 10 * 60 * 1000
const router = useRouter()
const cart = useCartStore()
const quote = ref(null), loading = ref(true), submitting = ref(false), confirming = ref(false), error = ref(''), checkoutToken = ref(''), orderId = ref(''), reference = ref('')
const form = ref({ firstName: '', lastName: '', email: '', phone: '' })
const errors = ref({})
let pollTimer = null, pollStartedAt = 0, pollRequestInFlight = false
const money = (minor) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: quote.value?.currency || 'NGN' }).format(Number(minor || 0) / 100)
const groups = computed(() => { const grouped = new Map(); for (const item of quote.value?.items || []) { const key = String(item.event_id); if (!grouped.has(key)) grouped.set(key, { event_id: item.event_id, event_title: item.event_title, items: [] }); grouped.get(key).items.push(item) } return [...grouped.values()] })
const stopPolling = () => { if (pollTimer) { window.clearInterval(pollTimer); pollTimer = null }; pollRequestInFlight = false }
const validate = () => { errors.value = {}; const required = { firstName: 'First name is required.', lastName: 'Last name is required.', email: 'Email is required.', phone: 'Phone number is required.' }; for (const [field, message] of Object.entries(required)) if (!String(form.value[field] || '').trim()) errors.value[field] = message; if (form.value.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.value.email.trim())) errors.value.email = 'Enter a valid email address.'; return !Object.keys(errors.value).length }
const expiredError = (err) => /expired|start a new checkout/i.test(Array.isArray(err?.response?.data?.errors?.checkout_token) ? err.response.data.errors.checkout_token.join(' ') : String(err?.response?.data?.errors?.checkout_token || err?.response?.data?.message || ''))
const loadQuote = async () => { if (cart.isEmpty) { error.value = 'Your cart is empty.'; loading.value = false; return }; loading.value = true; error.value = ''; try { quote.value = await quoteCheckout(cart.checkoutItems) } catch (err) { error.value = err?.response?.data?.message || 'We could not confirm the tickets in your cart.' } finally { loading.value = false } }
const finish = async (order) => { stopPolling(); rememberOrderToken(order.public_id, checkoutToken.value); cart.clearCart({ preserveCheckoutAttempt: true }); clearCheckoutAttempt(); confirming.value = false; await router.replace({ name: 'payment-success', params: { orderId: order.public_id } }) }
const handleOrder = async (order) => { if (!order) return false; if (['paid','payment_review'].includes(order.status)) { await finish(order); return true }; if (order.status === 'payment_failed') { stopPolling(); confirming.value = false; error.value = 'The payment was not completed. You can try again without losing your cart.'; return true }; if (order.status === 'expired') { stopPolling(); confirming.value = false; clearCheckoutAttempt(); checkoutToken.value = ''; error.value = 'Your ticket reservation expired. Your cart is still here — start payment again to reserve fresh availability.'; await loadQuote(); return true }; if (['cancelled','refunded'].includes(order.status)) { stopPolling(); confirming.value = false; error.value = `This order is ${order.status}.`; return true }; return false }
const inspectOrder = async () => { if (!orderId.value || pollRequestInFlight) return; pollRequestInFlight = true; try { await handleOrder(await getCheckoutOrder({ orderId: orderId.value, checkoutToken: checkoutToken.value })) } finally { pollRequestInFlight = false } }
const startPolling = () => { stopPolling(); confirming.value = true; pollStartedAt = Date.now(); pollTimer = window.setInterval(async () => { if (Date.now() - pollStartedAt > MAX_POLL_MS) { stopPolling(); confirming.value = false; error.value = 'Payment is taking longer than expected. If you completed payment, use “Check payment” below.'; return }; try { await inspectOrder() } catch {} }, POLL_INTERVAL_MS) }
const checkPayment = async () => { if (!reference.value || confirming.value) return; confirming.value = true; error.value = ''; try { const terminal = await handleOrder(await verifyCheckoutPayment({ reference: reference.value, checkoutToken: checkoutToken.value })); if (!terminal) error.value = 'Payment is not confirmed yet.' } catch (err) { error.value = err?.response?.data?.message || 'Payment is not confirmed yet.' } finally { if (!pollTimer) confirming.value = false } }
const pay = async () => { if (submitting.value || confirming.value || !validate()) return; submitting.value = true; error.value = ''; try { checkoutToken.value = getOrCreateCheckoutToken(); const result = await initializeCheckout({ checkoutToken: checkoutToken.value, visitorId: getVisitorId(), customer: { first_name: form.value.firstName.trim(), last_name: form.value.lastName.trim(), email: form.value.email.trim().toLowerCase(), phone: form.value.phone.trim() }, items: cart.checkoutItems }); const order = result?.order; if (!order?.public_id) throw new Error('Checkout did not return an order.'); orderId.value = order.public_id; rememberOrderToken(order.public_id, checkoutToken.value); if (await handleOrder(order)) return; reference.value = result?.payment?.reference || ''; const accessCode = result?.payment?.access_code || ''; if (!reference.value || !accessCode) throw new Error('Payment could not be opened. Please try again.'); const PaystackPop = await loadPaystack(); new PaystackPop().resumeTransaction(accessCode); startPolling() } catch (err) { if (expiredError(err)) { clearCheckoutAttempt(); checkoutToken.value = ''; await loadQuote(); error.value = 'Your previous reservation expired. Availability has been refreshed; start payment again.' } else error.value = err?.response?.data?.message || err?.message || 'We could not start checkout.' } finally { submitting.value = false } }
onMounted(() => { loadQuote(); loadPaystack().catch(() => {}) })
onBeforeUnmount(stopPolling)
</script>
<template><main class="checkout"><h1>Checkout</h1><div v-if="loading">Getting tickets…</div><div v-else class="grid"><form @submit.prevent="pay"><label v-for="(label,key) in {firstName:'First name',lastName:'Last name',email:'Email address',phone:'Phone number'}" :key="key">{{label}}<input v-model="form[key]" :type="key==='email'?'email':key==='phone'?'tel':'text'" :autocomplete="key==='firstName'?'given-name':key==='lastName'?'family-name':key"/><small v-if="errors[key]">{{errors[key]}}</small></label><button :disabled="submitting||confirming||!quote">{{submitting?'Starting payment…':confirming?'Confirming payment…':'Pay securely'}}</button><p v-if="confirming" aria-live="polite">Confirming payment… We’ll update this page as soon as your payment is confirmed.</p><button v-if="reference&&!submitting" type="button" :disabled="confirming" @click="checkPayment">Check payment</button><p v-if="error" role="alert">{{error}}</p></form><aside><h2>Order Summary</h2><section v-for="group in groups" :key="group.event_id"><h3>{{group.event_title}}</h3><div v-for="item in group.items" :key="item.ticket_type_id"><span>{{item.ticket_name}} · Qty: {{item.quantity}}</span><strong>{{money(item.line_total_minor)}}</strong></div></section><hr><strong>Total {{money(quote?.total_minor)}}</strong></aside></div></main></template>
<style scoped>.checkout{min-height:100vh;padding:50px 20px;background:var(--color-bg);color:var(--color-text)}.grid{max-width:950px;margin:auto;display:grid;grid-template-columns:1fr 1fr;gap:28px}.grid>*{padding:24px;border:1px solid var(--color-border);border-radius:16px;background:var(--color-surface)}label{display:grid;gap:7px;margin-bottom:14px;color:var(--color-muted)}input{min-height:44px;border:1px solid var(--color-border);background:var(--color-bg);color:var(--color-text);border-radius:8px;padding:0 10px}small{color:#ef4444}button{min-height:46px;margin-top:12px;padding:0 18px;border:0;border-radius:999px;background:var(--color-accent);color:#fff;font:inherit;font-weight:700;cursor:pointer}button:disabled{opacity:.55;cursor:not-allowed}aside section{padding:12px 0;border-bottom:1px solid var(--color-border)}aside section div{display:flex;justify-content:space-between;gap:18px;margin:9px 0}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style>
