<script setup>
import { computed,onMounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { useCartStore } from '@/stores/cart'
import { getVisitorId } from '@/services/eventViewService'
import { getOrCreateCheckoutToken,rememberOrderToken,clearCheckoutAttempt } from '@/utils/checkoutStorage'
import { loadPaystack } from '@/utils/paystack'
import { quoteCheckout,initializeCheckout,getCheckoutOrder,verifyCheckoutPayment } from '@/services/checkoutService'
const router=useRouter(),cart=useCartStore(),quote=ref(null),loading=ref(true),submitting=ref(false),confirming=ref(false),error=ref(''),token=ref(''),orderId=ref(''),reference=ref(''),form=ref({firstName:'',lastName:'',email:'',phone:''}),errors=ref({});let poll
const money=value=>new Intl.NumberFormat('en-NG',{style:'currency',currency:quote.value?.currency||'NGN'}).format(Number(value||0)/100);const groups=computed(()=>{const map=new Map();for(const item of quote.value?.items||[]){const key=String(item.event_id);if(!map.has(key))map.set(key,{event_id:item.event_id,event_title:item.event_title,items:[]});map.get(key).items.push(item)}return[...map.values()]});const validate=()=>{errors.value={};for(const key of ['firstName','lastName','email','phone'])if(!form.value[key].trim())errors.value[key]='Required.';return !Object.keys(errors.value).length};const load=async()=>{if(cart.isEmpty){error.value='Your cart is empty.';loading.value=false;return}try{quote.value=await quoteCheckout(cart.checkoutItems)}catch(err){error.value=err.response?.data?.message||'We could not confirm the tickets in your cart.'}finally{loading.value=false}};const finish=async order=>{rememberOrderToken(order.public_id,token.value);cart.clearCart({preserveCheckoutAttempt:true});clearCheckoutAttempt();clearInterval(poll);await router.replace({name:'payment-success',params:{orderId:order.public_id}})};const inspect=async()=>{const order=await getCheckoutOrder({orderId:orderId.value,checkoutToken:token.value});if(['paid','payment_review'].includes(order.status))await finish(order)};const check=async()=>{confirming.value=true;try{const order=await verifyCheckoutPayment({reference:reference.value,checkoutToken:token.value});if(['paid','payment_review'].includes(order.status))await finish(order)}catch(err){error.value=err.response?.data?.message||'Payment is not confirmed yet.'}finally{confirming.value=false}};const pay=async()=>{if(submitting.value||!validate())return;submitting.value=true;error.value='';try{token.value=getOrCreateCheckoutToken();const result=await initializeCheckout({checkoutToken:token.value,visitorId:getVisitorId(),customer:{first_name:form.value.firstName,last_name:form.value.lastName,email:form.value.email,phone:form.value.phone},items:cart.checkoutItems});const order=result.order;if(!order?.public_id)throw new Error('Checkout did not return an order.');orderId.value=order.public_id;rememberOrderToken(order.public_id,token.value);if(['paid','payment_review'].includes(order.status))return finish(order);reference.value=result.payment?.reference||'';const PaystackPop=await loadPaystack();new PaystackPop().resumeTransaction(result.payment?.access_code);confirming.value=true;poll=setInterval(()=>inspect().catch(()=>{}),2000)}catch(err){error.value=err.response?.data?.message||err.message||'We could not start checkout.'}finally{submitting.value=false}};onMounted(()=>{load();loadPaystack().catch(()=>{})})
</script><template><main class="checkout"><h1>Checkout</h1><div v-if="loading">Getting tickets…</div><div v-else class="grid"><form @submit.prevent="pay"><label v-for="(label,key) in {firstName:'First name',lastName:'Last name',email:'Email address',phone:'Phone number'}" :key="key">{{label}}<input v-model="form[key]" :type="key==='email'?'email':'text'" required><small v-if="errors[key]">{{errors[key]}}</small></label><button :disabled="submitting||confirming||!quote">{{submitting?'Starting payment…':confirming?'Confirming payment…':'Pay securely'}}</button><p v-if="confirming" aria-live="polite">Confirming payment… We’ll update this page as soon as your payment is confirmed.</p><button v-if="reference" type="button" @click="check">Check payment</button><p v-if="error">{{error}}</p></form><aside><h2>Order Summary</h2><section v-for="group in groups" :key="group.event_id"><h3>{{group.event_title}}</h3><div v-for="item in group.items" :key="item.ticket_type_id"><span>{{item.ticket_name}} · Qty: {{item.quantity}}</span><strong>{{money(item.line_total_minor)}}</strong></div></section><hr><strong>Total {{money(quote?.total_minor)}}</strong></aside></div></main></template><style scoped>.checkout{min-height:100vh;padding:50px 20px;background:var(--color-bg);color:var(--color-text)}.grid{max-width:950px;margin:auto;display:grid;grid-template-columns:1fr 1fr;gap:28px}.grid>*{padding:24px;border:1px solid var(--color-border);border-radius:16px;background:var(--color-surface)}label{display:grid;gap:7px;margin-bottom:14px;color:var(--color-muted)}input{min-height:44px;border:1px solid var(--color-border);background:var(--color-bg);color:var(--color-text);border-radius:8px;padding:0 10px}button{min-height:46px;margin-top:12px;padding:0 18px;border:0;border-radius:999px;background:var(--color-accent);color:#fff;font:inherit;font-weight:700}aside section{padding:12px 0;border-bottom:1px solid var(--color-border)}aside section div{display:flex;justify-content:space-between;margin:9px 0}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style>

