<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from "vue"
import { RouterLink } from "vue-router"
import { storeToRefs } from "pinia"
import { useEventStore } from "@/stores/events"
import EventCard from "@/components/EventCard.vue"
import SkeletonLoader from "@/components/SkeletonLoader.vue"
import OrganizerShowcase from "@/components/OrganizerShowcase.vue"
const eventStore=useEventStore();const {events,error}=storeToRefs(eventStore);const loadingEvents=ref(true);const homepageEvents=computed(()=>[...(events.value||[])].slice(0,6));
const setMeta=(selector,attribute,value)=>{let element=document.head.querySelector(selector);if(!element){element=document.createElement("meta");const match=selector.match(/(?:property|name)="([^"]+)"/);if(match)element.setAttribute(selector.includes("property=")?"property":"name",match[1]);document.head.appendChild(element)}element.setAttribute(attribute,value)};const applyLandingSeo=()=>{const title="KakaTickets | Find Events & Sell Tickets in Nigeria",description="Find events, buy tickets, create events and sell tickets with KakaTickets. See ticket sales, share event links, message attendees and check guests in.",canonicalUrl=`${window.location.origin}/`;document.title=title;setMeta('meta[name="description"]',"content",description);setMeta('meta[property="og:title"]',"content",title);setMeta('meta[property="og:description"]',"content",description);setMeta('meta[property="og:type"]',"content","website");setMeta('meta[property="og:url"]',"content",canonicalUrl);setMeta('meta[name="twitter:title"]',"content",title);setMeta('meta[name="twitter:description"]',"content",description);let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement("link");canonical.rel="canonical";document.head.appendChild(canonical)}canonical.href=canonicalUrl;document.getElementById("kakatickets-home-schema")?.remove();const schema=document.createElement("script");schema.id="kakatickets-home-schema";schema.type="application/ld+json";schema.textContent=JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":`${canonicalUrl}#website`,name:"KakaTickets",url:canonicalUrl,inLanguage:"en-NG",potentialAction:{"@type":"SearchAction",target:`${window.location.origin}/search?q={search_term_string}`,"query-input":"required name=search_term_string"}},{"@type":"Organization","@id":`${canonicalUrl}#organization`,name:"KakaTickets",url:canonicalUrl}]});document.head.appendChild(schema)};onMounted(async()=>{applyLandingSeo();try{await eventStore.fetchAllEvents(true,1,{allowFallback:false,skipCache:true})}catch(err){console.error("Unable to load events",err)}finally{loadingEvents.value=false}});onBeforeUnmount(()=>document.getElementById("kakatickets-home-schema")?.remove())
</script>
<template><div class="home-page"><section class="events-section" aria-labelledby="featured-events-title"><div class="landing-shell"><div class="section-heading"><div><p class="section-kicker">Go somewhere</p><h2 id="featured-events-title">Events worth leaving the house for.</h2></div><RouterLink to="/search">See all events →</RouterLink></div><div v-if="loadingEvents&&!homepageEvents.length" class="featured-skeleton"><SkeletonLoader type="grid" :count="4"/></div><div v-else-if="error&&!homepageEvents.length" class="simple-state"><strong>Events could not load.</strong><button @click="eventStore.fetchAllEvents(true,1,{allowFallback:false,skipCache:true})">Try again</button></div><div v-else-if="!homepageEvents.length" class="simple-state"><strong>Nothing is available right now.</strong><span>Please check back soon.</span></div><div v-else class="event-grid"><EventCard v-for="event in homepageEvents" :key="event.id" :event="event"/></div></div></section><OrganizerShowcase/><section class="final-cta"><div class="landing-shell final-cta-inner"><div><p class="section-kicker">For organisers</p><h2>Ready to sell your event?</h2></div><RouterLink to="/create-event">Create an event →</RouterLink></div></section></div></template>
<style scoped>.home-page{overflow:clip;background:var(--color-bg);color:var(--color-text)}.landing-shell{width:min(1320px,calc(100% - 40px));margin:auto}.events-section{padding:clamp(88px,9vw,132px) 0 clamp(104px,10vw,148px)}.section-heading{display:flex;align-items:end;justify-content:space-between;gap:28px;margin-bottom:clamp(34px,4vw,52px)}.section-heading h2,.final-cta h2{margin:0;color:var(--color-text);font-size:clamp(2rem,4vw,3.8rem);letter-spacing:-.045em;line-height:1.02}.section-kicker{margin:0 0 10px;color:var(--color-accent);font-size:.73rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.section-heading a{color:var(--color-accent);font-weight:750;text-decoration:none}.event-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));column-gap:clamp(30px,3vw,40px);row-gap:clamp(44px,5vw,64px)}.featured-skeleton{min-height:420px}.simple-state{min-height:180px;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:8px;padding:28px;border:1px solid var(--color-border);border-radius:18px;background:var(--color-surface);color:var(--color-muted)}.simple-state strong{color:var(--color-text)}.simple-state button{padding:9px 13px;border:1px solid var(--color-border);border-radius:999px;background:var(--color-tab-bg);color:var(--color-text);font:inherit;font-weight:700;cursor:pointer}.final-cta{padding:clamp(74px,9vw,124px) 0;background:var(--color-surface)}.final-cta-inner{display:flex;align-items:end;justify-content:space-between;gap:36px}.final-cta h2{font-size:clamp(2.5rem,5.1vw,5rem);line-height:.98}.final-cta a{padding:15px 20px;border-radius:999px;background:var(--color-accent);color:#fff;font-weight:750;text-decoration:none}@media(max-width:1040px){.event-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.landing-shell{width:min(100% - 28px,1320px)}.section-heading,.final-cta-inner{align-items:flex-start;flex-direction:column}.event-grid{grid-template-columns:1fr}}</style>


