<script setup>
import { onMounted, onUnmounted } from 'vue'
import { RouterLink } from 'vue-router'

const organizerCta = { path: '/create-event', query: { utm_source: 'homepage', utm_medium: 'website', utm_campaign: 'organizer_conversion', utm_content: 'sales_layers' } }
const browseCta = { path: '/search', query: { utm_source: 'homepage', utm_medium: 'website', utm_campaign: 'event_discovery', utm_content: 'sales_layers' } }
const problems = [
  { number: '01', title: 'Stop guessing where buyers come from.', copy: 'Give WhatsApp, Instagram and every campaign its own link. See the clicks and sales, then put your energy where people actually buy.', result: 'Know what is selling — and why.' },
  { number: '02', title: 'Stop running your event from scattered chats.', copy: 'Tickets, guest details, sales, messages and check-in stay together. Your team gets one clear place to work from.', result: 'Less confusion. Fewer costly mistakes.' },
  { number: '03', title: 'Stop looking at numbers that say nothing.', copy: 'See which ticket is moving, what needs attention and what to do next — in plain English, without becoming a data analyst.', result: 'Make the next move with confidence.' },
]
const flow = [
  { step: 'Create', copy: 'Build a professional event page, set ticket types and collect the guest details you need.' },
  { step: 'Share', copy: 'Use a trackable link for every place you promote — from WhatsApp to flyers.' },
  { step: 'Sell', copy: 'Let guests choose tickets and pay through a simple, secure checkout.' },
  { step: 'Run', copy: 'Watch sales, message guests and prepare QR check-in from one dashboard.' },
]
const faqs = [
  { question: 'Can I sell both free and paid tickets?', answer: 'Yes. Create free entry, paid tickets or several ticket levels for the same event.' },
  { question: 'Can I tell which promotion brought a sale?', answer: 'Yes. Separate campaign links help you compare buyer channels such as WhatsApp, Instagram and direct sharing.' },
  { question: 'Does Rush Hour work for different kinds of events?', answer: 'Yes. It supports concerts, conferences, comedy, theatre, sports, festivals, community events and more.' },
  { question: 'What happens after people buy?', answer: 'You can follow ticket performance, manage guest information, communicate updates and prepare QR-based event check-in.' },
]
const schemaId = 'rush-hour-homepage-schema'
let canonicalElement = null
onMounted(() => {
  const existingCanonical = document.querySelector('link[rel="canonical"]')
  if (existingCanonical) existingCanonical.setAttribute('href', 'https://rushhour.ng/')
  else { canonicalElement = document.createElement('link'); canonicalElement.rel = 'canonical'; canonicalElement.href = 'https://rushhour.ng/'; document.head.appendChild(canonicalElement) }
  document.getElementById(schemaId)?.remove()
  const schema = document.createElement('script')
  schema.id = schemaId
  schema.type = 'application/ld+json'
  schema.textContent = JSON.stringify({ '@context': 'https://schema.org', '@graph': [
    { '@type': 'WebSite', '@id': 'https://rushhour.ng/#website', url: 'https://rushhour.ng/', name: 'Rush Hour', description: 'Discover events and sell tickets online in Nigeria.', potentialAction: { '@type': 'SearchAction', target: 'https://rushhour.ng/search?q={search_term_string}', 'query-input': 'required name=search_term_string' } },
    { '@type': 'SoftwareApplication', name: 'Rush Hour', applicationCategory: 'BusinessApplication', operatingSystem: 'Web', url: 'https://rushhour.ng/', description: 'Event ticketing, promotion tracking, sales insights and guest management for event organizers.', offers: { '@type': 'Offer', price: '0', priceCurrency: 'NGN', description: 'Create an account and start building your event.' } },
    { '@type': 'FAQPage', mainEntity: faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) },
  ] })
  document.head.appendChild(schema)
})
onUnmounted(() => { document.getElementById(schemaId)?.remove(); canonicalElement?.remove() })
</script>

<template>
  <div class="sales-layers">
    <section class="promise-section" aria-labelledby="promise-title"><div class="sales-container promise-grid">
      <div><p class="eyebrow">For people who run events</p><h2 id="promise-title">A sold-out event should not depend on guesswork.</h2><p class="promise-lead">Rush Hour gives you one place to sell tickets, understand your buyers and run the day. You see what is working, what is not, and what to do next.</p><div class="promise-actions"><RouterLink :to="organizerCta" class="button button--primary">Create your event</RouterLink><a href="#how-rush-hour-works" class="text-link">See how it works <span aria-hidden="true">↓</span></a></div></div>
      <aside class="signal-card" aria-label="Example event sales insight"><div class="signal-card__top"><span>What Rush Hour tells you</span><span class="live-pill"><i></i> Live</span></div><div class="signal-score"><span>Event health</span><strong>82</strong><small>Strong momentum</small></div><div class="signal-list"><div><i></i><p><strong>VIP is nearly sold out.</strong><span>Use the real scarcity in your next post.</span></p></div><div><i></i><p><strong>WhatsApp brings the most buyers.</strong><span>Share there again before spending elsewhere.</span></p></div><div><i class="warn"></i><p><strong>Regular tickets need a push.</strong><span>A short offer can make the decision easier.</span></p></div></div></aside>
    </div></section>
    <section class="problems-section" aria-labelledby="problems-title"><div class="sales-container"><div class="section-intro"><p class="eyebrow">The real cost of doing it the hard way</p><h2 id="problems-title">Your event is already hard work. Selling it should not be.</h2><p>Every missed signal becomes wasted money, empty seats or another late-night spreadsheet.</p></div><div class="problem-grid"><article v-for="problem in problems" :key="problem.number" class="problem-card"><span class="problem-number">{{ problem.number }}</span><h3>{{ problem.title }}</h3><p>{{ problem.copy }}</p><strong><span aria-hidden="true">✓</span> {{ problem.result }}</strong></article></div></div></section>
    <section id="how-rush-hour-works" class="flow-section" aria-labelledby="flow-title"><div class="sales-container"><div class="section-intro section-intro--split"><div><p class="eyebrow">One simple system</p><h2 id="flow-title">From “we should do an event” to doors open.</h2></div><p>No complicated setup. No five different tools. Just a clear path from your first ticket to your first scan.</p></div><ol class="flow-list"><li v-for="(item, index) in flow" :key="item.step"><span>0{{ index + 1 }}</span><div><h3>{{ item.step }}</h3><p>{{ item.copy }}</p></div></li></ol></div></section>
    <section class="two-sides-section" aria-labelledby="two-sides-title"><div class="sales-container"><div class="section-intro section-intro--center"><p class="eyebrow">Better on both sides of the ticket</p><h2 id="two-sides-title">Professional for you. Effortless for your guests.</h2></div><div class="two-sides-grid"><article class="side-card"><span class="side-label">For organizers</span><h3>Run the business, not the chaos.</h3><ul><li>Professional event pages and flexible ticket types</li><li>Trackable campaign links and buyer-channel insights</li><li>Sales trends, ticket performance and clear next moves</li><li>Guest details, messages and check-in preparation</li></ul><RouterLink :to="organizerCta" class="card-link">Start selling tickets <span aria-hidden="true">→</span></RouterLink></article><article class="side-card side-card--guest"><span class="side-label">For guests</span><h3>Find it. Book it. Show up.</h3><ul><li>Discover events across music, comedy, sports and more</li><li>Clear event details and ticket choices</li><li>A simple, secure checkout</li><li>One smooth path from discovery to entry</li></ul><RouterLink :to="browseCta" class="card-link">Find your next event <span aria-hidden="true">→</span></RouterLink></article></div></div></section>
    <section class="faq-section" aria-labelledby="faq-title"><div class="sales-container faq-grid"><div class="faq-heading"><p class="eyebrow">Straight answers</p><h2 id="faq-title">Before you ask.</h2><p>Everything you need to know before putting your next event on Rush Hour.</p></div><div class="faq-list"><details v-for="faq in faqs" :key="faq.question"><summary>{{ faq.question }} <span aria-hidden="true">+</span></summary><p>{{ faq.answer }}</p></details></div></div></section>
    <section class="final-cta" aria-labelledby="final-cta-title"><div class="sales-container final-cta__inner"><p class="eyebrow">Your next event deserves a better system</p><h2 id="final-cta-title">People are ready to buy.<br />Make it easy for them.</h2><p>Create your page, share your links and know what to do next — all from Rush Hour.</p><div class="final-actions"><RouterLink :to="organizerCta" class="button button--light">Create your event</RouterLink><RouterLink :to="browseCta" class="button button--quiet">Browse events</RouterLink></div><small>No complicated setup. Start building in minutes.</small></div></section>
  </div>
</template>

<style scoped>
.sales-layers{--pink:var(--color-accent,#ec4899);--green:#38d996;color:var(--color-text)}.sales-container{width:100%;max-width:1320px;margin:auto;padding-inline:clamp(16px,1.8vw,24px)}.promise-section,.problems-section,.flow-section,.two-sides-section,.faq-section{padding:clamp(76px,9vw,132px) 0}.promise-section{background:linear-gradient(145deg,color-mix(in srgb,var(--color-surface) 92%,#170b19),var(--color-bg));overflow:hidden}.promise-grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(360px,.75fr);align-items:center;gap:clamp(48px,8vw,120px)}.eyebrow{margin:0 0 20px;color:var(--pink);font-size:.76rem;font-weight:750;letter-spacing:.15em;text-transform:uppercase}h2{margin:0;max-width:800px;font-size:clamp(2.35rem,5vw,5rem);line-height:.98;letter-spacing:-.055em}.promise-lead,.section-intro>p:last-child,.section-intro--split>p{margin:28px 0 0;max-width:650px;color:var(--color-muted);font-size:clamp(1.02rem,1.5vw,1.22rem);line-height:1.65}.promise-actions,.final-actions{display:flex;align-items:center;flex-wrap:wrap;gap:22px;margin-top:36px}.button{min-height:52px;display:inline-flex;align-items:center;justify-content:center;padding:0 24px;border-radius:999px;color:#fff;text-decoration:none;font-weight:700;transition:.2s}.button:hover{transform:translateY(-2px)}.button--primary{background:var(--pink);box-shadow:0 14px 34px color-mix(in srgb,var(--pink) 28%,transparent)}.text-link{color:var(--color-text);text-decoration:none;font-weight:650}.text-link span{color:var(--pink);margin-left:6px}
.signal-card{position:relative;padding:28px;border:1px solid color-mix(in srgb,var(--color-text) 10%,transparent);border-radius:24px;background:color-mix(in srgb,var(--color-surface) 91%,transparent);box-shadow:0 32px 80px #0003}.signal-card__top,.live-pill{display:flex;align-items:center;justify-content:space-between;gap:8px}.signal-card__top{color:var(--color-muted);font-size:.82rem;font-weight:650}.live-pill{padding:5px 9px;border-radius:99px;background:color-mix(in srgb,var(--green) 12%,transparent);color:var(--green)}.live-pill i{width:6px;height:6px;border-radius:50%;background:currentColor}.signal-score{display:grid;grid-template-columns:1fr auto;margin:36px 0 28px;padding-bottom:26px;border-bottom:1px solid color-mix(in srgb,var(--color-text) 9%,transparent)}.signal-score>span{align-self:end;color:var(--color-muted)}.signal-score strong{grid-row:span 2;font-size:4.5rem;line-height:.8;letter-spacing:-.08em}.signal-score small{margin-top:5px;color:var(--green);font-weight:650}.signal-list{display:grid;gap:22px}.signal-list>div{display:grid;grid-template-columns:9px 1fr;gap:13px}.signal-list i{width:8px;height:8px;margin-top:7px;border-radius:50%;background:var(--green)}.signal-list i.warn{background:#f0ad4e}.signal-list p,.signal-list strong,.signal-list span{display:block;margin:0}.signal-list strong{font-size:.94rem}.signal-list span{margin-top:4px;color:var(--color-muted);font-size:.82rem;line-height:1.45}
.section-intro{margin-bottom:clamp(44px,6vw,72px)}.section-intro h2{font-size:clamp(2.15rem,4.3vw,4rem)}.problem-grid{display:grid;grid-template-columns:repeat(3,1fr);border-block:1px solid var(--color-border)}.problem-card{min-height:390px;padding:38px clamp(22px,3vw,42px) 34px;border-right:1px solid var(--color-border);display:flex;flex-direction:column}.problem-card:last-child{border:0}.problem-number{color:var(--pink);font-size:.75rem;font-weight:750;letter-spacing:.14em}.problem-card h3{margin:52px 0 18px;font-size:clamp(1.4rem,2.1vw,2rem);line-height:1.12;letter-spacing:-.035em}.problem-card p{margin:0;color:var(--color-muted);line-height:1.65}.problem-card>strong{margin-top:auto;padding-top:36px;font-size:.88rem}.problem-card>strong span{color:var(--green);margin-right:7px}
.flow-section{background:var(--color-surface)}.section-intro--split{display:grid;grid-template-columns:1.25fr .75fr;gap:60px;align-items:end}.section-intro--split>p{margin:0 0 5px}.flow-list{list-style:none;margin:0;padding:0;border-top:1px solid var(--color-border)}.flow-list li{display:grid;grid-template-columns:80px 1fr;padding:31px 0;border-bottom:1px solid var(--color-border)}.flow-list li>span{color:var(--pink);font-size:.76rem;font-weight:750;padding-top:7px}.flow-list li div{display:grid;grid-template-columns:minmax(140px,.45fr) 1fr;gap:30px}.flow-list h3{margin:0;font-size:1.55rem}.flow-list p{margin:0;max-width:580px;color:var(--color-muted);line-height:1.6}.section-intro--center{text-align:center}.section-intro--center h2{margin:auto}.two-sides-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.side-card{min-height:500px;display:flex;flex-direction:column;padding:clamp(30px,4vw,54px);border:1px solid var(--color-border);border-radius:24px;background:var(--color-surface);overflow:hidden}.side-label{width:max-content;padding:7px 12px;border-radius:99px;background:color-mix(in srgb,var(--pink) 12%,transparent);color:var(--pink);font-size:.76rem;font-weight:750;text-transform:uppercase}.side-card h3{margin:34px 0 30px;font-size:clamp(2rem,3.3vw,3.2rem);line-height:1.02;letter-spacing:-.05em}.side-card ul{list-style:none;margin:0;padding:0;display:grid;gap:17px;color:var(--color-muted)}.side-card li{position:relative;padding-left:24px}.side-card li:before{content:'✓';position:absolute;left:0;color:var(--green)}.card-link{margin-top:auto;padding-top:38px;color:var(--color-text);text-decoration:none;font-weight:750}.card-link span{color:var(--pink)}
.faq-grid{display:grid;grid-template-columns:.7fr 1.3fr;gap:clamp(50px,8vw,120px)}.faq-heading h2{font-size:clamp(2.3rem,4vw,4rem)}.faq-heading>p:last-child{margin-top:24px;color:var(--color-muted)}.faq-list{border-top:1px solid var(--color-border)}.faq-list details{border-bottom:1px solid var(--color-border)}.faq-list summary{list-style:none;cursor:pointer;display:flex;justify-content:space-between;gap:24px;padding:25px 0;font-weight:650}.faq-list summary::-webkit-details-marker{display:none}.faq-list summary span{color:var(--pink);font-size:1.35rem}.faq-list details[open] summary span{transform:rotate(45deg)}.faq-list details p{margin:-4px 48px 25px 0;color:var(--color-muted);line-height:1.6}.final-cta{padding:clamp(80px,10vw,140px) 0;background:var(--pink);color:#fff;text-align:center}.final-cta__inner{display:flex;flex-direction:column;align-items:center}.final-cta .eyebrow{color:#ffffffb8}.final-cta h2{max-width:970px;font-size:clamp(2.5rem,6vw,5.7rem)}.final-cta p:not(.eyebrow){margin:28px auto 0;max-width:650px;color:#ffffffd1;font-size:1.08rem}.final-actions{justify-content:center}.button--light{background:#fff;color:#171218}.button--quiet{border:1px solid #ffffff80}.final-cta small{margin-top:22px;color:#ffffffaa}
@media(max-width:900px){.promise-grid,.section-intro--split,.faq-grid{grid-template-columns:1fr}.problem-grid{grid-template-columns:1fr}.problem-card{min-height:0;border-right:0;border-bottom:1px solid var(--color-border)}.problem-card h3{margin-top:30px}.problem-card>strong{margin-top:28px}.section-intro--split{gap:20px}}@media(max-width:680px){.promise-section,.problems-section,.flow-section,.two-sides-section,.faq-section{padding-block:72px}.promise-grid{grid-template-columns:minmax(0,1fr)}.two-sides-grid{grid-template-columns:1fr}.flow-list li{grid-template-columns:44px 1fr}.flow-list li div{grid-template-columns:1fr;gap:9px}.promise-actions{align-items:flex-start;flex-direction:column}}@media(prefers-reduced-motion:reduce){.button{transition:none}}
</style>
