<script setup>
import { computed } from 'vue'
import { RUSH_HOUR_DARK_LOGO } from '@/constants/brand'
const props=defineProps({dropdownOpen:{type:Boolean,required:true},events:{type:Array,default:()=>[]},activeEvent:{type:Object,default:null},currentManageView:{type:String,required:true},user:{type:Object,default:null}})
defineEmits(['toggle-dropdown','go-back','select-event','select-view'])
const initials=computed(()=>{const source=props.user?.name||props.user?.email||'User';return source.trim().split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]?.toUpperCase()).join('')||'U'})
const status=(value)=>({active:'Live',draft:'Draft',completed:'Completed',cancelled:'Cancelled'}[value]||value||'Event')
const navigation=[['overview','Overview'],['attendees','Attendees'],['share','Promote'],['promo','Discount codes'],['email','Message attendees'],['checkin','Door check-in'],['payout','Earnings'],['settings','Settings']]
</script>
<template><aside class="sidebar"><div class="sidebar-top"><img v-if="RUSH_HOUR_DARK_LOGO" :src="RUSH_HOUR_DARK_LOGO" alt="KakaTickets" class="sidebar-logo"><button type="button" class="sidebar-back" @click="$emit('go-back')">Back to site</button></div><div v-if="activeEvent" class="event-switcher"><button type="button" class="switcher-current" :aria-expanded="dropdownOpen" @click="$emit('toggle-dropdown')"><div class="switcher-thumb"><img v-if="activeEvent.image" :src="activeEvent.image" alt=""><span v-else>{{ activeEvent.title?.charAt(0)?.toUpperCase() || 'E' }}</span></div><div class="switcher-info"><div class="switcher-name">{{ activeEvent.title }}</div><div class="switcher-action">Change event</div></div><div class="switcher-arrow" :class="{open:dropdownOpen}">⌄</div></button><div class="events-dropdown" :class="{open:dropdownOpen}"><div class="dropdown-label">Your events</div><button v-for="event in events" :key="event.id" type="button" class="dropdown-event" :class="{active:Number(event.id)===Number(activeEvent.id)}" @click="$emit('select-event',event.id)"><div class="dropdown-thumb"><img v-if="event.image" :src="event.image" alt=""><span v-else>{{ event.title?.charAt(0)?.toUpperCase() || 'E' }}</span></div><div class="dropdown-event-copy"><div class="dropdown-event-name">{{ event.title }}</div><div class="dropdown-event-meta">{{ status(event.status) }}</div></div><div v-if="event.status==='active'" class="dropdown-live-dot"></div></button></div></div><nav class="sidebar-nav" aria-label="Event dashboard navigation"><button v-for="item in navigation" :key="item[0]" type="button" class="sidebar-nav-item" :class="{active:currentManageView===item[0]}" @click="$emit('select-view',item[0])">{{ item[1] }}</button></nav><div class="sidebar-user"><div class="sidebar-avatar">{{ initials }}</div><div><div class="sidebar-user-name">{{ user?.name || user?.email || 'Account' }}</div><div class="sidebar-user-role">Event organiser</div></div></div></aside></template>
